services:
  app:
    build: .
    container_name: google_auth_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5552:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  pg_data:
