services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5552:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
